// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52mbG8Anx_iHKqeGZtIQlTkFUX9AI5RY',
    appId: '1:1089095438215:web:e40b0fa654eb46c8be8d22',
    messagingSenderId: '1089095438215',
    projectId: 'myunify-d6c66',
    authDomain: 'myunify-d6c66.firebaseapp.com',
    storageBucket: 'myunify-d6c66.appspot.com',
    measurementId: 'G-PCJP5ETGLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmNuaWawkX5eLpk6erPbF67Oq6xVeMkI',
    appId: '1:1089095438215:android:40b4ebf049455b15be8d22',
    messagingSenderId: '1089095438215',
    projectId: 'myunify-d6c66',
    storageBucket: 'myunify-d6c66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq8qGEnQhNuDWVaLsd09QykH7vYFM1u_0',
    appId: '1:1089095438215:ios:f345f00286f25b8cbe8d22',
    messagingSenderId: '1089095438215',
    projectId: 'myunify-d6c66',
    storageBucket: 'myunify-d6c66.appspot.com',
    iosClientId: '1089095438215-u1aig3cb6h5taa10141ucacr943op0fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myunifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq8qGEnQhNuDWVaLsd09QykH7vYFM1u_0',
    appId: '1:1089095438215:ios:f345f00286f25b8cbe8d22',
    messagingSenderId: '1089095438215',
    projectId: 'myunify-d6c66',
    storageBucket: 'myunify-d6c66.appspot.com',
    iosClientId: '1089095438215-u1aig3cb6h5taa10141ucacr943op0fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myunifyApp',
  );
}
